spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}